{% set version = "1.1" %}

package:
  name: flit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: da823d4acae9bda42dcc0c7ab1d9be475a8a47aae5fd6dde63841d9f430ccb2f

build:
  number: 1
  script: FLIT_ROOT_INSTALL=1 {{PYTHON}} -m flit install --deps=none  # [not win]
  script: {{PYTHON}} -m flit install --deps=none  # [win]
  skip: True  # [py2k]
  entry_points:
    - flit = flit:main

requirements:
  host:
    - python
    - pip
    - docutils
    - requests
    - pytoml
    - zipfile36  # [py<36]
  run:
    - python
    - docutils
    - requests
    - requests_download
    - zipfile36  # [py<36]
    - pytoml
    - pip

test:
  imports:
    - flit
  commands:
    - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf
