travis:
  secure:
    BINSTAR_TOKEN: blj5TULXunAae/YQa4GzSmr7zlo+u8s3ZrDZWtMWcG/9awDBrtbWhd3WoEvwdYTsvkdDv5ecPJ5aNi2fGcmlezXob7bWAIBw5NgicBm0QoW0qf+KBx73VuPhPSJ0Xp18u4b493KC42raHdCgnWahn26yDXmctBJUMlqfvHa0vm457plLkljWL6FWL8PWA9D0rOdRouvrOZ/ZFFG1LsvNp7PWLR8G3Ui5ptnV50PO5VJlJYG9qmZOxFMRqLb/t2SK9HK+MYVamx1UIuVLVrgzbrU2yUF6fP8hIUxWWqor+Hf1/QTjpHupbJUD6xN2mp0woUEEH0MHDoQdv6VOh5TmKJbwIRdEcHDCY1+t9HiSgeUze/7k30pHa/kmJV5sKXL6wSfdrtBXEw4g8Y+2xAd/DIgARi3eKV/51632k4/J6AypXy7CV3ye0CxU4iEP3I9TjLHXqEvVYj7FdX1h4WiOjVSBsEgpweK/IJensi94VxvKell+qrF0/fWvN265EowUTP36wUz0mm6JEucQGHM0Sa2QFutT8/Vx6FBkWNOyiygqlHc6daE5iyBiEL+Q5L6A+Um4g6aO3bzCZ3EVsHcTGeHhtZlw1kmkJukkkJyFAGN8/31B/cEHuHydMIuyA41gPkYVBkpuFIm+1MyiJ09s4aMIJW0KbZFTc4Bd7ZkdtWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
